package LabSession_july_29;

public class ExceptionHandling01 

{

    public static void main(String[] args) 

    {

        try

        {

            System.out.println("Try Block");

        }

       // System.out.println("-----");// error after try block there should be catch block

        catch (Exception e) 

        {

            System.out.println("Catch Block");

        }

    }

}
 